### ISSUE TITLE
Bug: "Restart" binding immediately reboots the system instead of spawning restart confirmation dialog

### ISSUE THREAD

**Issue by leviport** [pop-os/mouse-configurator#10]
Not sure if this was intentional, but I think the "Restart" binding would be much better for users if it spawned the same confirmation dialog that you get when clicking Restart from System menu > Power off / log out > Restart. If a user actually _does_ frequently want to restart their machine via a mouse binding, the confirmation dialog would help prevent accidental restarts and lost work. As it is now, hitting a button bound to Restart instantly reboots the machine, without any opportunity to save unsaved work beforehand.

**Comment by ids1024** [comment]
This is emitting a `RESTART` USB keycode. I guess this is probably treated the same way as a restart button on a desktop, and is handled by ACPI rather than Gnome?

I don't see a Gnome keybinding that would restart with a prompt, so I don't know if there's a solution. We could leave as is, or remove the option.

**Comment by TheCodeTherapy** [comment]
@ids1024 it should probably be bound to `gnome-session-quit --reboot`

**Comment by ids1024** [comment]
Okay, so there's a command for that. But the mouse can't directly execute a command (unless it does something very dubious like a macro opening a run dialog and typing that). It would have to be bound to something in Gnome's keybinding settings.

We could add some custom binding if there's not something by default, but I don't know how we'd want to handle that.

**Comment by TheCodeTherapy** [comment]
@ids1024 I was thinking of adding a keyboard shortcut bound to `gnome-session-quit --reboot`, but I think that might be too intrusive (having the configurator app add a custom keyboard shortcut to the system that can also be triggered by pressing the same keys we might set as default to it.  In case @leviport agrees, I believe we should remove it for now. Having a mouse key to restart the system with no confirmation by the user can't be a smooth or good experience.
