### ISSUE TITLE
Scroll Left and Scroll Right buttons on the SVG are somewhat confusing

### ISSUE THREAD

**Issue by christian-salgado** [pop-os/mouse-configurator#14]
Redesign to show the arrow legends printed on the mouse and include them in the SVG. The SVG still matches the current design with placement, so no adjustment to button location should be required. 

![Scroll Wheel Button Redesign(4)](https://user-images.githubusercontent.com/88847836/172194393-4774f72a-9647-4b49-a30c-98b7e1e02c65.png)

SVG Files - 
![mouse-light](https://user-images.githubusercontent.com/88847836/172193304-4557abd7-f23e-4a58-98e3-b707283e29f1.svg)
![mouse-dark](https://user-images.githubusercontent.com/88847836/172193309-def9f454-6bde-4a5d-9389-12cdaa3e4437.svg)

**Comment by ids1024** [comment]
This seems better, and hopefully will be clearer to users. Updated in https://github.com/pop-os/mouse-configurator/commit/13a7b85bc5066a84f1536a8ecd385e37eac62832.

**Comment by leviport** [comment]
Fix confirmed, looks great!
