### ISSUE TITLE
Zoom In will not apply to any keys

### ISSUE THREAD

**Issue by Socialhappiness** [pop-os/mouse-configurator#17]
When trying to assign the 'zoom in' feature in app/browser controls, the application defaults to 'zoom out' and applies that action to the button instead. I received one report of this and confirmed on my personal machine the same behavior.

**Comment by khdc2** [comment]
I just purchased the HP Dev One  Linux laptop with HP creator mouse and can confirm it does not work on either the Logitech MX Master 3S as well
