### ISSUE TITLE
Mouse Configurator Spacing Outline

### ISSUE THREAD

**Issue by christian-salgado** [pop-os/mouse-configurator#3]
The horizontal spacing for the configurator. 

![Spacing Guide](https://user-images.githubusercontent.com/88847836/168321929-e59b3fb8-3e5d-49f9-9df9-7029c7294b8b.png)

The vertical spacing for the configurator. 
![Vertical Spacing](https://user-images.githubusercontent.com/88847836/168324521-20b78b40-5064-4eef-8a16-425da5cd35cf.png)

**Comment by ids1024** [comment]
I think everything here was implemented. Closing.
