### ISSUE TITLE
Bug: Clicking "About this mouse" spawns a new info window every time it is clicked

### ISSUE THREAD

**Issue by leviport** [pop-os/mouse-configurator#5]
This allows several instances of the same dialog to be opened simultaneously. 

https://user-images.githubusercontent.com/13512097/171916848-9989df62-e370-4220-95d8-bbc7a79a0c59.mp4

**Comment by ids1024** [comment]
Ah, I forgot to make the dialog modal. Simple enough to fix.

**Comment by leviport** [comment]
Fix confirmed, looks good now!
