### ISSUE TITLE
Bug: Some binding descriptions overlap the diagram of the mouse

### ISSUE THREAD

**Issue by leviport** [pop-os/mouse-configurator#7]
Some binding descriptions are long enough that they overlap the image of the mouse. The longest ones are display brightness up/down and move to workspace above/below.
![2022-06-03_13-34](https://user-images.githubusercontent.com/13512097/171937231-21b17f19-9a89-49d8-9b9a-7a31b62b182f.png)

**Comment by WatchMkr** [comment]
That could work with some adjustment... "Display Brightness Up" and "Display Brightness Down" are a little shorter. "Workspace Up" and "Workspace Down" are good.

Separate but something to consider, with COSMIC DE, we'd like to enable vertical or horizontal workspaces which makes the language tricky. We may want to use "Workspace Next" and "Workspace Previous" or similar to start making it orientation agnostic,

**Comment by christian-salgado** [comment]
Are we able to define the define the text alignment inside the buttons? Use set_alignment for the buttons so they're right-aligned on the left side, and left-aligned on the right side. Using the white space on the sides to our advantage, we could have a high character limit. 

https://docs.gtk.org/gtk3/method.Button.set_alignment.html

An example of it - 
![overlap the diagram redesign](https://user-images.githubusercontent.com/88847836/172217089-9fa89d6d-bce5-4aee-b0ff-55cf2e1af82a.png)


Here's an alternative with the shortening the svg lines and centering the buttons with the lines. 
![overlap the diagram redesign(1)](https://user-images.githubusercontent.com/88847836/172217462-42ebb48f-66cf-463f-91ce-cdc8025229ed.png)

**Comment by ids1024** [comment]
> Are we able to define the define the text alignment inside the buttons? Use set_alignment for the buttons so they're right-aligned on the left side, and left-aligned on the right side. 

That's kind of how it already works, but reversed. Currently the labels on the left side are positioned based on their bottom left corner, while the ones on the right are positioned based on their bottom right. This way it would be aligned by the other side, and vertically centered (I think https://docs.gtk.org/gtk4/enum.ConstraintAttribute.html#center_y will do that).

For the current version, I kind of awkwardly manually adjusted the positions of labels in code until they seemed right (specifying the position of the end of each line as a percentage of width and height)... I guess I should see if that can be done in a better way if we need to change them all.

**Comment by ids1024** [comment]
> I guess I should see if that can be done in a better way if we need to change them all.

Okay, it looks like this can cleanly be done by pixel positions, after multiplying by pixel height/width (there were issues with how positioning worked in earlier versions, but it seems I got it to work in a sane way).

I think that alternate version should work. I'll need the the svg and the x/y positions for the end of each line, as shown in Inkscape.

**Comment by maria-komarova** [comment]
If we go this route, there are two smaller considerations, mostly visual:
-  Alignment for the sake of readability - having a staircase always makes people's eyes hunt for what they need. 
- Window resizing. Currently the window stop resizing when it reaches content boundaries. If we continue to do the same while allowing the labels to grow outwards from the diagram, then we can end up with a large window that won't size down. 

For the first one we can at least make sure all the lines start in the same spot on each side. 
For window resizing, not sure what we can do. But that's probably less of a concern unless we do have translations for this app.

**Comment by christian-salgado** [comment]
(Updated to reflect the new alignment so there's so staircase affect.) 
Here's the x/y position for the alternative version as well as the SVG if we decide to go with it. 

Left Click -  x294 y234
Middle Click - x515 y187
Right Click - x565 y234
Left Scroll - x294 y267
Right Scroll - x565 y267
Forward - x262 y348
Super - x262 y377
Back - x262 y406


![mouse-light(2)](https://user-images.githubusercontent.com/88847836/172255736-dc7bf17f-e6cb-48b6-ac2a-164e5f4da3a8.svg)

![mouse-dark(2)](https://user-images.githubusercontent.com/88847836/172255747-26b3db6b-e3a0-41fa-b7a7-c2ad4e219d56.svg)

**Comment by ids1024** [comment]
Those coordinates don't seem to be quite right...

![Screenshot from 2022-06-06 17-00-34](https://user-images.githubusercontent.com/2263150/172268372-00bfccb7-ec42-413c-9bac-d19c210b2c18.png)

**Comment by christian-salgado** [comment]
I highlighted the point in Inkscape and got the coordinates, unless I miss understood. I can give you the Figma coordinates instead- 


Left Click - x121 y64
Middle Click - x342 y17
Right Click - x392 y64
Left Scroll - x121 y97
Right Scroll - x392 y97
Forward - x89 y178
Super - x89 y207
Back - x89 y236


![image](https://user-images.githubusercontent.com/88847836/172412750-c7f8f90d-66ed-48bb-92fd-cf6129790d5c.png)

**Comment by ids1024** [comment]
Not sure why you were seeing different values in Inkscape, but anyway, https://github.com/pop-os/mouse-configurator/commit/55fccae33c321288e9cc912accbcf78dbb40885e updates this:

![Screenshot from 2022-06-07 08-20-17](https://user-images.githubusercontent.com/2263150/172418867-ae0a5f81-bb05-4bdc-9ec6-2b31e48ffb5a.png)

I guess to match the mockup there should be some padding on the sides of the labels to space them from the lines (which is easy to add), but I kind of like it like this.

**Comment by christian-salgado** [comment]
That was odd, not sure either. But I would add an 8-pixel padding from the line.

**Comment by ids1024** [comment]
![Screenshot from 2022-06-07 08-34-49](https://user-images.githubusercontent.com/2263150/172421786-4cee60d5-432b-4ccb-8cb5-19248c2c6ec9.png)

**Comment by ids1024** [comment]
Closing as resolved, since we seem to be happy with this design.
